### ISSUE TITLE
Composer not showing after connecting my app with my twitter

### ISSUE THREAD

**Issue by barcennas** [twitter/twitter-kit-ios#70]
Hi

I'm currently having trouble presenting the composer in my app, when I click the twitter button my apps opens twitter and shows a screen asking me to connect my account to my app, and after I click the connect button the screen closes and goes back to my app, but after that nothing is happening, I was expecting to se a twitter popup that let me compose a tweet, am i doing something wrong?

Thanks.

**Comment by barcennas** [comment]
I forgot to mention, I'm not using twitter login for my app, i just want to enable the option to share a photo and text to twitter within my app.

**Comment by harjeetk** [comment]
My share composer gets stuck after I try to add a tweet in it.

**Comment by mohit-kapadia** [comment]
You will have whitelist the URLs check this 
https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

**Comment by littleylv** [comment]
Hi, I'm having the same problem. Has anyone solved it?

**Comment by littleylv** [comment]
I found this which works: https://github.com/twitter/twitter-kit-ios/issues/49#issuecomment-383596480

**Comment by katejlee** [comment]
The above method accepts url which will work.
Better fix is to update callback URL on apps.twitter.com to add something like:
`twitterkit-<consumerKey>://` 

And instead of returning `YES` on `openURL`, you can do normal:
`[[Twitter sharedInstance] application:application openURL:url options:options]`

This was announced Early May.
https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342
